export const MUTATIONS_CONSTANTS = {
  SET_CARDS: "SET_CARDS",
  PUSH_CARD: "PUSH_CARD",
  SET_IS_LOADING_GAME: "SET_IS_LOADING_GAME",
  SET_IS_FLIPPED_CARD: "SET_IS_FLIPPED_CARD",
  SET_IS_CHECKED_CARD: "SET_IS_CHECKED_CARD",
  SET_GAME_MODE: "SET_GAME_MODE",
};

export const ACTIONS_CONSTANTS = {
  GET_CARDS: "GET_CARDS",
  CHECK_CARDS: "CHECK_CARDS",
};
