export const MUTATIONS_CONSTANTS = {
  SET_USER: "SET_USER",
  SET_USERS: "SET_USERS",
  SET_IS_FETCHING_USER: "SET_IS_FETCHING_USER",
  SET_IS_FETCHING_USERS: "SET_IS_FETCHING_USERS",
  SET_IS_LOADING: "SET_IS_LOADING"
};

export const ACTIONS_CONSTANTS = {
  POST_USER: "POST_USER",
  GET_USERS: "GET_USERS"
};
